using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Bari.Core.Generic;
using Bari.Core.Model;

namespace Bari.Plugins.VsCore.VisualStudio
{
    /// <summary>
    /// Default implementation for the <see cref="IProjectGuidManagement"/> interface
    ///
    /// <para>New GUIDs are derived from the suite, module and project names, so a clean, which deletes
    /// the cache, does not give every generated project file a new GUID. GUIDs already in the cache
    /// are kept.</para>
    /// </summary>
    public class DefaultProjectGuidManagement: IProjectGuidManagement
    {
        // Namespace of the name-based (RFC 4122 version 5) GUIDs generated by bari
        private static readonly Guid guidNamespace = new Guid("b7a3cf24-1c03-475e-9b3f-8944bbd44e02");

        private readonly Lazy<IFileSystemDirectory> cacheRoot;
        private readonly Suite suite;
        private readonly object sync = new object();
        private bool isInitialized;
        private readonly IDictionary<Project, Guid> projectMap = new Dictionary<Project, Guid>();
        private readonly IDictionary<Module, Guid> moduleMap = new Dictionary<Module, Guid>();

        /// <summary>
        /// Initializes the GUID management service
        /// </summary>
        /// <param name="cacheRoot">Cache root directory</param>
        /// <param name="suite">Active suite</param>
        public DefaultProjectGuidManagement([CacheRoot] Lazy<IFileSystemDirectory> cacheRoot, Suite suite)
        {
            Contract.Requires(cacheRoot != null);
            Contract.Requires(suite != null);

            this.cacheRoot = cacheRoot;
            this.suite = suite;
        }        

        /// <summary>
        /// Gets the GUID associated with the given project
        /// </summary>
        /// <param name="project">The bari project model</param>
        /// <returns>Always returns the same GUID for the same project, also after the cache is cleaned.</returns>
        public Guid GetGuid(Project project)
        {
            lock(sync)
            {
                if (!isInitialized)
                    InitializeFromCache();

                Guid result;
                if (!projectMap.TryGetValue(project, out result))
                {
                    result = NameBasedGuid(ProjectKey(project));
                    projectMap.Add(project, result);

                    SaveToCache();
                }

                return result;
            }
        }

        /// <summary>
        /// Gets the GUID associated with the given module
        /// </summary>
        /// <param name="module">The bari module model</param>
        /// <returns>Always returns the same GUID for the same module, also after the cache is cleaned.</returns>
        public Guid GetGuid(Module module)
        {
            lock (sync)
            {
                if (!isInitialized)
                    InitializeFromCache();

                Guid result;
                if (!moduleMap.TryGetValue(module, out result))
                {
                    result = NameBasedGuid(ModuleKey(module));
                    moduleMap.Add(module, result);

                    SaveToCache();
                }

                return result;
            }
        }

        private void InitializeFromCache()
        {
            if (cacheRoot.Value.Exists("guids"))
            {
                using (var reader = cacheRoot.Value.ReadTextFile("guids"))
                {
                    string line = reader.ReadLine();
                    while (line != null)
                    {
                        string[] parts = line.Split('=');
                        var name = parts[0];

                        if (name.StartsWith("module "))
                        {
                            var module = FindModule(name.Substring(7));
                            if (module != null)
                                moduleMap.Add(module, Guid.Parse(parts[1]));
                        }
                        else
                        {
                            var project = FindProject(name);
                            if (project != null)
                                projectMap.Add(project, Guid.Parse(parts[1]));
                        }

                        line = reader.ReadLine();
                    }
                }
            }

            isInitialized = true;
        }

        private Project FindProject(string moduleAndProject)
        {
            return (from module in suite.Modules
                    where moduleAndProject.StartsWith(module.Name + '.', StringComparison.InvariantCultureIgnoreCase)
                    let projectName = moduleAndProject.Substring(module.Name.Length + 1)
                    select module.GetProjectOrTestProject(projectName)).FirstOrDefault();
        }

        private Module FindModule(string module)
        {
            return suite.HasModule(module) ? suite.GetModule(module) : null;
        }

        private static string ProjectKey(Project project)
        {
            return project.Module.Name + "." + project.Name;
        }

        private static string ModuleKey(Module module)
        {
            return "module " + module.Name;
        }

        private Guid NameBasedGuid(string key)
        {
            return NameBasedGuid(guidNamespace, suite.Name + "/" + key);
        }

        /// <summary>
        /// Creates an RFC 4122 version 5 (SHA-1, name-based) GUID
        /// </summary>
        /// <param name="namespaceId">Namespace of the name</param>
        /// <param name="name">Name within the namespace</param>
        /// <returns>Returns the same GUID for the same namespace and name.</returns>
        public static Guid NameBasedGuid(Guid namespaceId, string name)
        {
            var namespaceBytes = namespaceId.ToByteArray();
            SwapByteOrder(namespaceBytes);
            var nameBytes = Encoding.UTF8.GetBytes(name);
            var data = new byte[namespaceBytes.Length + nameBytes.Length];
            Buffer.BlockCopy(namespaceBytes, 0, data, 0, namespaceBytes.Length);
            Buffer.BlockCopy(nameBytes, 0, data, namespaceBytes.Length, nameBytes.Length);

            byte[] hash;
            using (var sha1 = SHA1.Create())
                hash = sha1.ComputeHash(data);

            var bytes = new byte[16];
            Array.Copy(hash, bytes, 16);
            bytes[6] = (byte)((bytes[6] & 0x0F) | 0x50); // version 5
            bytes[8] = (byte)((bytes[8] & 0x3F) | 0x80); // RFC 4122 variant
            SwapByteOrder(bytes);
            return new Guid(bytes);
        }

        // Converts between the RFC 4122 (big-endian) and the System.Guid byte order.
        private static void SwapByteOrder(byte[] guid)
        {
            Swap(guid, 0, 3);
            Swap(guid, 1, 2);
            Swap(guid, 4, 5);
            Swap(guid, 6, 7);
        }

        private static void Swap(byte[] bytes, int left, int right)
        {
            var tmp = bytes[left];
            bytes[left] = bytes[right];
            bytes[right] = tmp;
        }

        private void SaveToCache()
        {
            using (var writer = cacheRoot.Value.CreateTextFile("guids"))
            {
                foreach (var pair in projectMap)
                {
                    string key = ProjectKey(pair.Key);
                    string value = pair.Value.ToString("B");
                    writer.WriteLine("{0}={1}", key, value);
                }

                foreach (var pair in moduleMap)
                {
                    string key = ModuleKey(pair.Key);
                    string value = pair.Value.ToString("B");
                    writer.WriteLine("{0}={1}", key, value);
                }
            }
        }
    }
}